@extends('layouts.app')
@section('content')
<div class="container">
      @include('partials.modal-login-user')
      <div class="row mt-5">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus, odit blanditiis eos officiis ipsum nemo quo. Dolore corrupti minima eum consectetur iusto nulla perferendis dolor nihil magni omnis aperiam tempore doloremque, consequatur aspernatur accusamus fugiat ipsam assumenda veniam voluptates repellendus minus cumque necessitatibus cupiditate esse? Vitae laborum ex aliquam et cumque ut sunt illo maiores voluptas facere adipisci totam id ea veniam animi officiis repudiandae, asperiores rerum odio consequatur voluptate doloremque magni labore? Optio voluptate id quam temporibus nobis libero repudiandae. Iusto laudantium fugiat ratione laboriosam corporis quaerat doloribus nostrum magnam esse, molestiae officia sunt suscipit sint eius dicta necessitatibus reiciendis omnis, perferendis rerum. Voluptate esse dignissimos quaerat recusandae iusto nisi, dolor vel distinctio officiis tenetur, illo pariatur veritatis? Alias facere fugiat, eum laborum dolorum totam, veniam nulla nemo error sunt quo esse et voluptates, impedit iusto? Voluptatibus, expedita perspiciatis? Quasi reiciendis ad odio necessitatibus labore similique explicabo, veniam ex. Obcaecati facilis, illo totam quod ipsa sunt dolorem odit quasi reprehenderit cumque a deleniti modi exercitationem corporis at consequuntur ipsam sapiente sequi temporibus quae laudantium tempore vel aliquid? Est nemo molestiae quas, magnam vitae tenetur sunt odit adipisci labore nihil, corporis laborum doloribus neque. Dolorem a sapiente quisquam eum iusto aliquid eveniet ut, eius nihil rem ipsa numquam blanditiis id maxime, placeat, possimus doloremque sequi. Voluptatem illo explicabo reiciendis minima? Iste quae enim totam rerum voluptatem, vero voluptatum minima nobis sit quo, praesentium eius eligendi quibusdam distinctio architecto maiores beatae a quia vel ea itaque? Asperiores quos dolore ex voluptatibus repellat nesciunt voluptas expedita ratione veniam inventore accusantium necessitatibus architecto voluptates, tempora consectetur facilis esse? Corporis sunt qui atque placeat! Doloremque neque non dignissimos quis, eaque deserunt sint! Quis eligendi obcaecati explicabo totam fugit temporibus rem earum, molestiae alias quae modi voluptatum sit beatae doloribus ipsa iusto reiciendis reprehenderit et.
      </div>
      @include('partials.footer')
</div>
@endsection
